# Generated by Django 5.1.4 on 2024-12-29 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0007_alter_studentdtl_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelperStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.IntegerField(choices=[('1', '総力戦\\大決戦'), ('2', '合同火力演習'), ('3', '占領戦'), ('4', '制約解除決戦')])),
                ('sort_no', models.IntegerField(choices=[(1, '1'), (2, '1'), (3, '1')])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='students.student')),
            ],
        ),
    ]
