# Generated by Django 5.1.4 on 2024-12-31 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('he1pers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helperstudent',
            name='content',
            field=models.CharField(choices=[('1', '総力戦/大決戦'), ('2', '合同火力演習'), ('3', '占領戦'), ('4', '制約解除決戦')], max_length=1),
        ),
        migrations.AlterField(
            model_name='helperstudent',
            name='sort_no',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')]),
        ),
    ]
