# Generated by Django 5.1.4 on 2024-12-19 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impl_order', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=15, unique=True)),
                ('icon_path', models.CharField(max_length=100, unique=True)),
                ('wiki_link', models.CharField(blank=True, max_length=240, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('1', '★'), ('2', '★★'), ('3', '★★★'), ('4', '★★★★'), ('5', '★★★★★'), ('6', '固有★★'), ('7', '固有★★★')], max_length=1)),
                ('level', models.IntegerField(choices=[])),
                ('ex', models.IntegerField(choices=[])),
                ('ns', models.IntegerField(choices=[])),
                ('ss', models.IntegerField(choices=[])),
                ('ps', models.IntegerField(choices=[])),
                ('equip_1', models.IntegerField(choices=[])),
                ('equip_2', models.IntegerField(choices=[])),
                ('equip_3', models.IntegerField(choices=[])),
                ('lim_health', models.IntegerField(choices=[])),
                ('lim_attach', models.IntegerField(choices=[])),
                ('lim_heal', models.IntegerField(choices=[])),
                ('relationship', models.IntegerField(choices=[])),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='students.studentdtl')),
            ],
        ),
    ]
