# Generated by Django 5.1.4 on 2024-12-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_studentdtl_icon_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='equip_1',
            field=models.IntegerField(choices=[], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='equip_2',
            field=models.IntegerField(choices=[], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='equip_3',
            field=models.IntegerField(choices=[], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='ex',
            field=models.IntegerField(choices=[], default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.IntegerField(choices=[], default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='lim_attach',
            field=models.IntegerField(choices=[], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='lim_heal',
            field=models.IntegerField(choices=[], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='lim_health',
            field=models.IntegerField(choices=[], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='ns',
            field=models.IntegerField(choices=[], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='ps',
            field=models.IntegerField(choices=[], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='rank',
            field=models.CharField(choices=[('1', '★'), ('2', '★★'), ('3', '★★★'), ('4', '★★★★'), ('5', '★★★★★'), ('6', '固有★★'), ('7', '固有★★★')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='relationship',
            field=models.IntegerField(choices=[], default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='ss',
            field=models.IntegerField(choices=[], default=0),
        ),
    ]
