# Generated by Django 5.1.4 on 2025-01-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teacher_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='friend_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
